#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@openhei-ai/script"
import pkg from "../package.json"

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")
const skipDashboard = process.argv.includes("--skip-dashboard")
const skipModels = process.argv.includes("--skip-models")

const rebuildDashboard = process.argv.includes("--rebuild-dashboard") || Script.release
const refreshModels = process.argv.includes("--refresh-models") || Script.release

const app = path.resolve(dir, "../../packages/app")
const dash = path.join(app, "dist", "index.html")

const reuseDashboard =
  !rebuildDashboard && (process.argv.includes("--reuse-dashboard") || singleFlag || fs.existsSync(dash))
const reuseModels = !refreshModels && (process.argv.includes("--reuse-models") || singleFlag)

const modelsUrl = process.env.OPENHEI_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const snapshot = path.join(dir, "src/provider/models-snapshot.ts")
if (skipModels || (!refreshModels && fs.existsSync(snapshot)) || (reuseModels && fs.existsSync(snapshot))) {
  if (fs.existsSync(snapshot)) {
    console.log("Using existing models-snapshot.ts")
  } else {
    throw new Error("--skip-models/--reuse-models set but models-snapshot.ts is missing")
  }
} else {
  try {
    const modelsData = process.env.MODELS_DEV_API_JSON
      ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
      : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
    await Bun.write(
      snapshot,
      `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
    )
    console.log("Generated models-snapshot.ts")
  } catch (e) {
    if (fs.existsSync(snapshot)) {
      console.log("Using existing models-snapshot.ts")
    } else {
      throw e
    }
  }
}

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) return false
      if (item.avx2 === false) return baselineFlag
      if (item.abi !== undefined) return false
      return true
    })
  : allTargets

if (skipDashboard) {
  if (!fs.existsSync(dash)) {
    throw new Error("--skip-dashboard set but packages/app/dist is missing")
  }
} else if (rebuildDashboard || !reuseDashboard || !fs.existsSync(dash)) {
  console.log("building dashboard")
  await $`bun run build`.cwd(app)
}

if (!singleFlag) {
  await $`rm -rf dist`
}

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`rm -rf dist/${name}`
  await $`mkdir -p dist/${name}/bin`
  await $`cp -r ../../packages/app/dist dist/${name}/dashboard`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/openhei`,
      execArgv: [`--user-agent=openhei/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENHEI_VERSION: `'${Script.version}'`,
      OPENHEI_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENHEI_WORKER_PATH: workerPath,
      OPENHEI_CHANNEL: `'${Script.channel}'`,
      OPENHEI_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}`)
    }
  }
  await $`gh release upload v${Script.version} dist/*.zip dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`.nothrow()
}

export { binaries }
